@startuml Carta
skinparam classAttributeIconSize 0

interface Carta {
    +aplicarModificador(Tarot tarot)
    +obtenerPuntaje() : Puntaje
    +esDelMismoPalo(Carta carta) : bool
    +obtenerNumero() : int
    +sos(Carta carta) : bool
}

class CartaInglesa {
-valor: int
-numero: int
+CartaInglesa(int numero, Palo palo)
+aplicarModificador(Tarot t)
+esDelMismoPalo(Carta carta) : bool
+obtenerNumero() : int
-obtenerPalo() : Palo
+obtenerPuntaje(): Puntaje
+sos(CartaInglesa c): bool
+comprar()
}

abstract class Tarot{
#juego: Juego
+{abstract}obtenerPuntaje(Puntaje p): Puntaje
+sosParaEsteJuego(Juego juego): bool
}

CartaInglesa *-- Tarot :tiene

interface Palo {
+{abstract}esDeEstePalo(Palo p): bool
}

CartaInglesa *-- Palo :tiene

class Trebol {
+esDeEstePalo(Palo p): bool
}

class Corazon {
+esDeEstePalo(Palo p): bool
}

class Pica {
+esDeEstePalo(Palo p): bool
}

class Diamante {
+esDeEstePalo(Palo p): bool
}

Trebol .up.|> Palo
Corazon .up.|> Palo
Diamante .down.|> Palo
Pica .down.|> Palo
CartaInglesa .left.|> Carta

@enduml