@startuml Comodin
skinparam classAttributeIconSize 0

interface Modificador{
+{abstract} aplicarModificador(Puntaje puntaje, Juego juego)
}

class Aleatorio{
- probabilidad : int
+{method} Aleatorio(int probabilidad)
+{method} sucede() : bool
}

class Comodin{
#cantidad : double
#juego : Juego
+{method} Comodin(double cantidad, Aleatorio probabilidad, Juego juego)
+{abstract} {method} aplicarModificador(Puntaje puntaje, Juego juego)
#{method} puedeAplicarse() : bool
}

class ComodinCombinacion{
+{method}ComodinCombinacion(List<Comodin> comodines)
+{method} aplicarModificador(Puntaje puntaje, Juego juego)
}

class SumaMultiplicador{
+SumaMultiplicador(double cantidad, Juego juego, Aleatorio probabilidad)
+SumaMultiplicador(double cantidad, Aleatorio probabilidad)
+SumaMultiplicador(double cantidad, Juego juego)
+SumaMultiplicador(double cantidad)
+aplicarModificador(Puntaje puntaje, Juego juego)
}


class SumaMultiplicadorDescarte{
+SumaMultiplicadorDescarte(double cantidad, Aleatorio probabilidad)
+SumaMultiplicadorDescarte(double cantidad)
+aplicarModificador(Puntaje puntaje, Juego juego)
}


class SumaPuntos{
+SumaPuntos(double cantidad, Juego juego, Aleatorio probabilidad)
+SumaPuntos(double cantidad, Aleatorio probabilidad)
+SumaPuntos(double cantidad, Juego juego)
+SumaPuntos(double cantidad)
+aplicarModificador(Puntaje puntaje, Juego juego)
}

class SumaPuntosDescarte{
+SumaPuntosDescarte(int cantidad, Aleatorio probabilidad)
+SumaPuntosDescarte(int cantidad)
+aplicarModificador(Puntaje puntaje, Juego juego)
}

Comodin *-- Aleatorio
Comodin .down.|> Modificador
ComodinCombinacion "1" -up-> "*" Comodin
ComodinCombinacion .right.|> Modificador
SumaMultiplicador -left-|> Comodin
SumaMultiplicadorDescarte -down-|> Comodin
SumaPuntos -right-|> Comodin
SumaPuntosDescarte -down-|> Comodin
@enduml