@startuml Juego
skinparam classAttributeIconSize 0

abstract Juego {
#modificador: Tarot
-{static}juegos: List<Juego>
+{static}ChequearJuego(List<Carta>): Juego
+{abstract}puntuarMano(List<Carta>): Puntaje
+{abstract}sosJuego(List<Carta>): bool
#puntuarCartas(ArrayList<Carta> c, Puntaje puntajeBase): Puntaje
-aplicarTarotALaIntancia(Tarot t)
+aplicarTarot(Tarot t)
}


class CartaAlta {
+puntuarMano(List<Carta>): Puntaje
+sosJuego(List<Carta>): bool
}

class Par {
+puntuarMano(List<Carta>): Puntaje
+sosJuego(List<Carta>): bool
}

class DoblePar {
+puntuarMano(List<Carta>): Puntaje
+sosJuego(List<Carta>): bool
}

class Trio {
+puntuarMano(List<Carta>): Puntaje
+sosJuego(List<Carta>): bool
}

class Escalera {
+puntuarMano(List<Carta>): Puntaje
+sosJuego(List<Carta>): bool
}

class Color {
+puntuarMano(List<Carta>): Puntaje
+sosJuego(List<Carta>): bool
}

class FullHouse {
+puntuarMano(List<Carta>): Puntaje
+sosJuego(List<Carta>): bool
}

class Poker {
+puntuarMano(List<Carta>): Puntaje
+sosJuego(List<Carta>): bool
}

class EscaleraDeColor {
+puntuarMano(List<Carta>): Puntaje
+sosJuego(List<Carta>): bool
}

class EscaleraReal  {
+puntuarMano(List<Carta>): Puntaje
+sosJuego(List<Carta>): bool
}

CartaAlta -up-|> Juego
Par -up-|> Juego
DoblePar -up-|> Juego
Trio -up-|> Juego
Escalera -left-|> Juego::aplicarTarot
Color -right-|> Juego
FullHouse -down-|> Juego
Poker -down-|> Juego
EscaleraDeColor -down-|> Juego
EscaleraReal -down-|> Juego


@enduml Clases