@startuml ManoYMazo
skinparam classAttributeIconSize 0
class Mazo {
-cartas: List<Carta>
-cartasDescartadas: List<Carta>
+repartirCartas(int cantidad): List<Carta>
+mezclar()
}

class Mano {
-maxCartas: int
-cartas: List<Carta>
-cartasSelecionadas: List<Carta>
-juego: Juego
+Mano(int cantidadDeCartas)
+agregarCarta(Carta c)
+agregarCartas(List<Carta> c)
+quitarCarta(Carta c)
+quitarCartas(List<Carta> c)
+elegirCarta(Carta c)
+obtenerCantidadDeCartas(): int
+obtenerCarta(Carta c): Carta
+jugarMano(): int
}

Mano ..> Mazo: "usa"
@enduml