@startuml RondaManoYMazo
skinparam classAttributeIconSize 0

class Ronda{
-puntajeASuperar : Puntaje
-puntajesObtenidos : List<Puntaje>
-descartes : int
- manos : int
- tienda : Tienda
+Ronda(Puntaje puntajeASuperar, int manos, int descartes, Mazo mazo, Tienda tienda)
+agregarComodin(Modificador comodin)
+descartarMano(ArrayList<Carta> cartasSeleccionadas, Juego juego, Comodinera comodinera)
+elegirCarta(Carta c)
+jugarMano(ArrayList<Carta> cartasSeleccionadas, Juego juego, Comodinera comodinera)
+modificarCarta(Carta c, Tarot t)
+modificarJuego(Tarot t)
-pasoLaRonda() : bool
-puedeSeguirJugando() : bool
+obtenerCartas() : List <Carta>
+comprar (Modificador comodin)
+comprar (Carta carta)
+comprar (Tarot tarot)
}

class Mazo {
-cartas: List<Carta>
-cartasDescartadas: List<Carta>
+agregarCarta(Carta C)
+agregarCartas(List<Carta> c)
+repartirCartas(int cantidad): List<Carta>
+mezclar()
}

class ManoDe8 {
-maxCartas: int
-maxCartasSeleccionadas: int
-cartas: List<Carta>
-cartasSelecionadas: List<Carta>
-juego: Juego
-comodines: List<Modificador>
+ManoDe8(int cantidadDeCartas)
+agregarCarta(Carta c)
+agregarCartas(List<Carta> c)
+agregarComodin(Modificador comodin)
+descartarMano() : Puntaje
+elegirCarta(Carta c)
+jugarMano() : Puntaje
+modificarCarta(Carta c, Tarot t)
+modificarJuego(Tarot t)
+obtenerCantidadDeCartas(): int
+obtenerCarta(Carta c): Carta
+quitarCarta(Carta c)
+quitarCartas(List<Carta> c)
+obtenerCartas() : List <Carta>
}

interface Mano{
+agregarCarta(Carta carta)
+agregarCartas(ArrayList<Carta> cartas)
+quitarCarta(Carta carta)
+quitarCartas(ArrayList<Carta> cartas)
+descartarMano(ArrayList<Carta> cartasSeleccionadas, Juego juego, Comodinera comodinera) : Puntaje
+jugarMano(ArrayList<Carta> cartasSeleccionadas, Juego juego, Comodinera comodinera) : Puntaje
+obtenerCantidadDeCartas() : int
+obtenerCarta(Carta cartaBuscada) : Carta
+modificarCarta(Carta carta, Tarot tarot)
+modificarJuego(Tarot tarot)
+obtenerCartas() : List <Carta>
}

ManoDe8 ..|> Mano
Ronda o-- Mano : tiene
Ronda --> Mazo : tiene
@enduml