@startuml Tarot
skinparam classAttributeIconSize 0

abstract class Tarot{
#juego: Juego
+{abstract}obtenerPuntaje(Puntaje p): Puntaje
+sosParaEsteJuego(Juego juego): bool
}

class Sumador {
-puntos: int
-multiplicador: int
+Sumador(int puntos, double multiplicador, Juego juego)
+Sumador(int puntos, double multiplicador)
+obtenerPuntaje(Puntaje p): Puntaje
}

class SinTarot {
+SinTarot(Juego juego)
+obtenerPuntaje(Puntaje p): Puntaje
}

class CambiadorDePuntos {
-puntos: int
+CambiadorDePuntos(int puntos)
+CambiadorDePuntos(int puntos, Juego juego)
+obtenerPuntaje(Puntaje p): Puntaje
}

class CambiadorDeMultiplicador {
-multplicador: int
+CambiadorDeMultiplicador(int multplicador)
+CambiadorDeMultiplicador(int multplicador, Juego juego)
+obtenerPuntaje(Puntaje p): Puntaje
}

Sumador -right-|> Tarot
SinTarot -left-|> Tarot
CambiadorDePuntos -up-|> Tarot
CambiadorDeMultiplicador --|> Tarot


@enduml