@startuml casoDeUso3
title "test03 El Jugador Si Posee Un Comodin Que Suma 10 Puntos Por Descarte Al Descartar Sume La Cantidad Correcta"

participant "TestCase" as TestCase

activate TestCase

TestCase -> "esperado:Puntaje" as esperado **: new Puntaje(10,1)
activate esperado
TestCase <-- esperado : esperado
deactivate esperado

TestCase -> "c:Comodin" as comodin **: new SumaPuntosDescarte(10,"")

activate comodin
comodin -> "a:Aleatorio" as aleatorio **: new Aleatorio(1)
activate aleatorio
comodin <-- aleatorio
deactivate aleatorio
comodin -> "sinJuego:SinJuego" as sinJuego ** : new SinJuego()
activate sinJuego
comodin <-- sinJuego
deactivate sinJuego
TestCase <-- comodin : c
deactivate comodin

TestCase -> "mano:ManoDe8" as mano **: new ManoDe8()
activate mano
TestCase <-- mano : mano
note right of TestCase: creamos 5 cartas que forman una escalera
TestCase -> mano : agregarCartas(cartas)
deactivate mano

TestCase -> "sel:Saleccionadas" as sel ** : new SeleccionadasBalatro()
loop para cada carta
TestCase -> sel : seleccionarCarta(carta)
end

TestCase -> "comodinera:Comodinera" as comodinera **: new()
activate comodinera
TestCase -> comodinera : agregarComodin(c)
deactivate comodinera


TestCase -> mano : descartarMano(seleccionadas, comodinera)
activate mano
mano -> mano : quitarCartas(sel)
mano -> sel: vaciarCartas()
mano -> sel : obtenerJuego()
activate sel
sel -> "Juego" : chequearJuego(sel)
activate Juego

loop para cada juego
Juego -> juegoActual : colocarCartas(sel)
activate juegoActual
Juego -> juegoActual : obtenerMayor()
Juego <-- juegoActual : sinJuego
deactivate juegoActual
end

sel <-- Juego : sinJuego
deactivate Juego

mano <-- sel : sinJuego
deactivate sel

mano -> Juego : obtenerPuntaje()
activate Juego
mano <-- Juego : Puntaje(0,1)
deactivate Juego

mano -> comodinera : aplicarComodines(resultado, sinJuego)
loop para cada comodin
comodinera -> "Comodin" : aplicarModificador(resultado, sinJuego)
end
TestCase <-- mano : resultado:Puntaje
deactivate mano


TestCase -> esperado : tenesMismoPuntaje(resultado)
activate esperado
TestCase <-- esperado : true
deactivate esperado

deactivate TestCase
@enduml